name: firestore_entity
description: A Firestore helper library for binding and mapping documents to class entities.
version: 0.3.1
homepage: https://abdulaziz.dev
repository: https://github.com/abdulaziz-mohammed/firestore_entity

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.6
  rxdart: ^0.27.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
