name: firestore_entity
description: A Firestore helper library for binding and mapping documents to class entities.
version: 0.2.1
homepage: https://abdulaziz.dev
repository: https://github.com/abdulaziz-mohammed/firestore_entity

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^3.0.1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  rxdart: ^0.24.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
